---
- name: Install PostgreSQL
  ansible.builtin.apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL is running
  ansible.builtin.service:
    name: postgresql
    enabled: yes
    state: started

- name: Install common library
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ default_library }}"
  tags: library

- name: Create application database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: myapp
    state: present

- name: Create database user
  community.postgresql.postgresql_user:
    name: myuser
    password: mypassword
    state: present
    expires: infinity