---
- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present

- name: Ensure PostgreSQL is running
  ansible.builtin.service:
    name: postgresql
    enabled: yes
    state: started

- name: Configure PostgreSQL authentication
  become_user: postgres
  lineinfile:
    path: /etc/postgresql/*/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+peer'
    line: 'local all postgres md5'
    backrefs: yes
  notify: reload postgresql

- name: Set postgres password
  become_user: postgres
  postgresql_user:
    name: postgres
    password: "{{ postgres_password }}"

- name: Create application database
  become_user: postgres
  postgresql_db:
    name: myapp
    encoding: UTF8
    login_user: postgres
    login_password: "{{ postgres_password }}"

- name: Create database user
  community.postgresql.postgresql_user:
    name: myuser
    password: mypassword
    state: present
    expires: infinity