---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600 # Обновлять кэш, если ему больше 1 часа
  tags: update

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"
  tags: packages

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  tags: config

- name: Copy MOTD template
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
  notify: flush motd # Уведомляем handler
  tags: config